### ISSUE TITLE
Improve and better integrate changes from `suggest`

### ISSUE THREAD

**Issue by mxsdev** [stateful/runme#123]
Here is a compilation of things we may want to do before releasing the `suggest branch` feature.

**Higher Priority / Simple to Implement**:

 - API being down should have a better UX - currently, we get: `failed to run command: Post "f/graphql": Post "/auth/cli": unsupported protocol scheme`
   - Might want to point users to the Discord/GH Issue page here if this happens?
 - Invalid auth token should have a better UX - currently, we get: `failed to run command: returned error 401 Unauthorized: {"message":"JWT error","code":"unauthorized"}`
   - We should probably just redirect to the auth flow and get a new token in this case
 - `getDefaultConfigHome`, used for API token storage, should be configurable and should probably use `os.UserConfigDir` instead of `os.UserHomeDir`

@sourishkrout I didn't talk about the API here, since I'm assuming its good on your end.

I'll add anything else brought up to this list going forward 👍

**Comment by adambabik** [comment]
I agree that most of the improvements at this moment would be around the UX and messages.

> getDefaultConfigHome, used for API token storage, should be configurable and should probably use os.UserConfigDir instead of os.UserHomeDir

I think it can be worth doing sooner than later. Otherwise, we will need to write some code for backward compatibility. Also, changing this will trigger re-authentication for everyone, even those using Stateful's CLI. Please note that currently, `runme` and `stateful` CLIs rely on the same authentication token stored in the same place.

**Comment by sourishkrout** [comment]
> Please note that currently, `runme` and `stateful` CLIs rely on the same authentication token stored in the same place.

That's high up on the priority list 👍 .

**Comment by duvanmonsa** [comment]
resolved item 1, 2 in this PR https://github.com/stateful/runme/pull/209

**Comment by sourishkrout** [comment]
Done.
