### ISSUE TITLE
Don't allow circular executions

### ISSUE THREAD

**Issue by christian-bromann** [stateful/runme#256]
Given the following markdown file, e.g. `CONTRIBUTING.md`:

    # Contributing

    Run this:

    ```sh { name=task }
    runme run task
    ```

This currently causes Runme to execute the same task over and over again. This obviously can happen in much more complex forms:

    # Contributing

    Run this:

    ```sh { name=taskA }
    runme run taskB
    ```

    ```sh { name=taskB }
    runme run taskC
    ```

    ```sh { name=taskC }
    runme run taskA
    ```

I've been running into this and only was able to delete all running processes via:

```sh
killall runme
```

It doesn't seem like killing the main runme process has an effect on following Runme processes which is why I had to use `killall` to actually get rid of all runme processes.

Given users could execute runme tasks based on certain conditions I think it is impossible to 100% determine such recursions. Maybe we can leave this up to the responsibility of the user but offer a `runme killall` command that securely shuts down all running runme processes.

**Comment by mxsdev** [comment]
Stopping the task probably has no effect because the loop will spawn processes faster (or at an equivalent rate) as they are shut down.

How would a command like `runme killall` operate a an implementation level? Is there a clear foolproof way to distinguish runme processes from other processes?

The best solution I can think of is to keep track of runme process depth in an environment variable, and refuse to run once the depth gets too high.

**Comment by christian-bromann** [comment]
> How would a command like `runme killall` operate a an implementation level? Is there a clear foolproof way to distinguish runme processes from other processes?

We could keep a temporary file around that stores all `pid`s and clear them once executed.

> The best solution I can think of is to keep track of runme process depth in an environment variable, and refuse to run once the depth gets too high.

Sounds like a reasonable approach 👍
