### ISSUE TITLE
Prompting for exports is broken in the TUI in certain cases

### ISSUE THREAD

**Issue by mikeage** [stateful/runme#286]
When I run the attached file (see the next line), I get this output. Note that the default command for `SPOT_INSTANCE_REQUEST` is cut off, and indeed, does not work. 

[README.broken_prompt.md](https://github.com/stateful/runme/files/11645499/README.broken_prompt.md)

This is a regression caused by #253 ; prior to this PR, it correctly ran the command (with no option to change / override the export, but that's ok; I never wanted to do that).

```
$ runme --filename README.broken_prompt.md
runme 1.2.2

> export-spotinstancerequest README.broken_prompt.md
    # Stop the instance (...)



Set Environment Variable "SPOT_INSTANCE_REQUEST": $(aws ec2 describe-spot-instance-requests --filters 'Nam


Set Environment Variable "INSTANCE_ID": $(aws ec2 describe-spot-instance-requests --spot-instance-request-ids $SPOT_INSTANCE_REQUEST | jq -r '.SpotInstanceRequests[].InstanceId')

bash: unexpected EOF while looking for matching `''
exit code: 2
```

**Comment by sourishkrout** [comment]
Hi, @mikeage. Thanks for reporting this! Sorry for breaking your workflow. This issue was introduced to bring the `TUI` on par with the VS Code extension.

While we're fixing the underlying issue, you can work around the bug by adding a `promptEnv=false` option to the fenced code block like so:

3c3
< ```bash { promptEnv=false }
---
> ```bash

GitHub issues are great! If you ever want a direct line to the team, we're all available in the Runme Community server: https://discord.gg/runme.

**Comment by duvanmonsa** [comment]
Hi @mikeage I apologize for introducing this bug, The fix is here https://github.com/stateful/runme/pull/283 we will release it as soon as possible. thank you so much for reporting.

**Comment by mikeage** [comment]
Thanks!

**Comment by sourishkrout** [comment]
@mikeage should be fixed as of v1.2.4. Let us know how if you see any other issues.

Btw, we're looking to introduce a more fundamental change into how the CLI works. The idea is to consider all markdown files contained in the project (git-repo) or directory tree as opposed to `README.md` or `--filename` only. You can test drive it with setting the `--project` flag to `--project ""` to default to git-repo or `--project .` to use the current directory as root of the dir/file tree. We are still working out the UX and in the spirit of not breaking you again, I'd love to hear your thoughts. Btw, if your code blocks won't show up it's likely due to `--allow-unnamed`. Without code blocks without names are filtered out. Still working out the UX before making `--project` default.

Any feedback here or in Discord would be much appreciated! Thank you.

**Comment by mikeage** [comment]
Cool, I'll check it out :-)

**Comment by sourishkrout** [comment]
Heads up @mikeage! We [release 1.3.0 today](https://github.com/stateful/runme/releases/tag/v1.3.0), which makes "project mode" default. Overall the idea is to make running tasks in Runme worry-free in terms of in what exact file the code block is located.

Runme will no longer default to `README.md` instead, it will scan the current working directory tree for all markdown files. By default, only explicitly named code blocks (overwrite with `--allow-unnamed`) will be considered. If you'd rather use the old behavior you can add `--filename README.md` to all commands, which will narrow it down to a single file.

A few improvements will come soon, including considering all unnamed code blocks in case there aren't any with names. We are publishing a blog post that explains the benefits and differences more comprehensively tomorrow—just wanted to give you a heads-up.

**Comment by mikeage** [comment]
Thanks for the heads up! I'm away on vacation, so I probably won't be using this for a while, but I really appreciate your reaching out proactively :-)

**Comment by sourishkrout** [comment]
> Thanks for the heads up! I'm away on vacation, so I probably won't be using this for a while, but I really appreciate your reaching out proactively :-)

Of course! We didn't want to break you again. Enjoy your vacay!

**Comment by sourishkrout** [comment]
Btw, here's the relevant blog post (https://runme.dev/blog/tasks-over-files-in-runme-cli) for when you're back from vacation!

**Comment by mikeage** [comment]
Just realized I never responded here... new version is working great, and I love this project :-)
