### ISSUE TITLE
[feat] Add option to open the md/mdx file in default code editor 

### ISSUE THREAD

**Issue by sarvex** [stateful/runme#321]
Some scenarios required to edit the file directly in the default text editor. editing website md/mdx files in react/svelte/astro. 

Right now this is not supported. Ideally there should be an options to add a button to "switch to default editor"

**Comment by christian-bromann** [comment]
@sarvex thanks for raising the issue.

You can switch between both views with the button in VS Code, see https://docs.runme.dev/features#runme-ux

Is this solving your use case?

**Comment by sarvex** [comment]
@christian-bromann apologies I missed that, silly me

**Comment by sarvex** [comment]
On a second perusal, the behaviour of the button is inconsistent, `Run` switches the editor in place, whereas `MDX` opens a new editor in a split window on the right. 

@christian-bromann the behaviour should be consistent for both views and IMHO it should be changing view in-place. Shall I open a new `bug` for this?

**Comment by admc** [comment]
I often have this scenario where for the next few hours I will be working on docs for example, and only want to see/edit raw markdown. As far as I know, right now the only ways to switch the default mode are to:

- right click on a markdown, goto "open with", then click "configure default editor for .md" and change it to text editor
- disable or uninstall runme

I can't find a way to get to configure directly from command palette. So that first path, should probably be in the runme docs (if it currently isn't).

However, in this scenario it would be convenient if there was an additional "easy button" somewhere in the UI that changed the default editor to "text editor" and then when I'm done I can click it again, and turn the default back to "runme". I would certainly use this.

Also, regarding the behavior of the current markdown button behavior, and having watched some folks use it, they always close the notebook because they dont want the screen real estate used up by having both. Maybe that behavior should simply be to replace the notebook with text.

wdyt @sarvex @christian-bromann ?

**Comment by sarvex** [comment]
> However, in this scenario it would be convenient if there was an additional "easy button" somewhere in the UI that changed the default editor to "text editor" and then when I'm done I can click it again, and turn the default back to "runme". I would certainly use this.

This would be easy if `runme` just remembered the last state of the editor. And seriously I expected it to do the same. But as it turns out `runne` does not keep track of the state. Should be another bug
 
> Also, regarding the behavior of the current markdown button behavior, and having watched some folks use it, they always close the notebook because they dont want the screen real estate used up by having both. Maybe that behavior should simply be to replace the notebook with text.

IMHO edit-in-place is the only way to do it

**Comment by sarvex** [comment]
@christian-bromann I assigned a keymap to deal with the bug, it is just a workaround, till **stateful** fixes the issue

```json
  {
    "key": "ctrl+enter",
    "command": "workbench.action.toggleEditorType"
  }
```

Add the above in your user keymaps and then you can switch between editor types in-place no separate windows will open. 


@admc let me know if you need help fixing the issues.

**Comment by sourishkrout** [comment]
Hi @sarvex. There's a new setting (`runme.actions.openViewInEditor`) for the extension to change the behavior to what you desire (please see below). It's got two options, `split` (default; existing behavior) and `toggle`, which basically runs `workbench.action.toggleEditorType`.

The big downside I see, which is why it's opt-in for now, is that toggling back and forth will wipe the notebooks execution state, which is dangerous. We might introduce a third option to open the raw text editor as a separate document.

Anyways, please give a spin and let us know what you think.

<img width="807" alt="image" src="https://github.com/stateful/runme/assets/250527/e829dc6a-ef41-4efa-a09c-e54ec968ef16">

**Comment by sarvex** [comment]
@sourishkrout thanks for all the help.

**Comment by sourishkrout** [comment]
> @sourishkrout thanks for all the help.

Of course! Thanks for using Runme.
