### ISSUE TITLE
runme cli ignores document-level option shell

### ISSUE THREAD

**Issue by ruzickap** [stateful/runme#367]
Hello.

I tried to set the `shell` value for all my commands in the document, but it seems like runme doesn't use that value. 

Example:

<pre>
$ mkdir /tmp/test
$ cd /tmp/test

$ cat > my.md << \EOF
---
shell: /usr/local/bin/bash
---

# Test

RunMe test:

```sh { promptEnv=false }
echo $SHELL
```
EOF

$ runme run echo-shell
/bin/zsh
</pre>

As you can see from the commands above - even when I specified exact shell `shell: /usr/local/bin/bash` the command `echo $SHELL` inside the markdown file executed by runme is still showing me `/bin/zsh` :-(

Thank you for looking at it...

**Comment by pastuxso** [comment]
I was able to reproduce the problem within the VS Code Extension.

![image](https://github.com/stateful/runme/assets/43882/15248274-41e9-4f0a-a60c-c1c4524d86d4)

**Comment by sourishkrout** [comment]
This had me confused for a minute. The problem here is that `$SHELL` won't ever change since it's the default shell passed down from the system. What you do want to print is `echo $0` where `$0` is the path of the binary used during execution and specific to the instance of execution.

@ruzickap @pastuxso please see the canonical examples/test-cases for reference: https://github.com/stateful/runme/blob/main/examples/frontmatter/shells/BASH.md

As per my explanation, please confirm that this is in fact not a bug.

**Comment by ruzickap** [comment]
Thank you @sourishkrout 
You are right ...
This is not a bug - thank you for your explanation :-)
Closing...

**Comment by sourishkrout** [comment]
No worries. I still appreciate you taking the time to file the bug. We're very much interested in squashing them.

**Comment by pastuxso** [comment]
Thank you all for explaining it to me, I now understand clearly.

![image](https://github.com/stateful/runme/assets/43882/05f3fd5e-6dfd-43e5-ad30-efe3da6e4ec6)
