### ISSUE TITLE
Work thru goreleaser deprecation warnings

### ISSUE THREAD

**Issue by sourishkrout** [stateful/runme#378]
Bottom of https://github.com/stateful/runme/actions/runs/6249835863

Also the json schema balks at:

<img width="980" alt="image" src="https://github.com/stateful/runme/assets/250527/5b1e68bb-aa6f-4ae8-824e-682bf8159bf5">

**Comment by sourishkrout** [comment]
> If no one else is looking at this yet I might take a crack at it tonight. I recently did a little work with github actions and go releaser for my terraform provider so it's fresh in my mind.

Be my guest, please!

**Comment by catdevman** [comment]
@sourishkrout  well I got to where I can run the release on tags! https://github.com/catdevman/runme/actions/runs/6322034405 
I was wondering what vscode extension you're using? Can we work on making a list of all the things that need updated.

- [ ] goreleaser version 
- [ ] nfpms.replacements deprecated https://goreleaser.com/deprecations/#nfpmsreplacements
- [ ] archives.rlcp deprecated https://goreleaser.com/deprecations/#archivesrlcp
- [ ] archives.replacements deprecated https://goreleaser.com/deprecations/#archivesreplacements
- [ ] set-output deprecated https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ (this should be fixed with the goreleaser version from what I could tell)

Anything else?
