### ISSUE TITLE
Casting int to uint spells danger

### ISSUE THREAD

**Issue by sourishkrout** [stateful/runme#413]
In an error scenario, `exitCode` can return `-1`, which will incorrectly be turned into 4294967295.

https://github.com/stateful/runme/blob/a1052d7a98398918e7a9f1e53ce040560e36a575/internal/runner/service.go#L470

What's the fix? As far as I remember, negative exit codes aren't actually valid.

PS: Still need to investigate the underlying issue causing the exit code to be returned as -1 (stack trace below).

```
signal: hangup
github.com/stateful/runme/internal/runner.(*command).ProcessWait
	/Users/sourishkrout/Projects/stateful/oss/runme/internal/runner/command.go:498
github.com/stateful/runme/internal/runner.(*runnerService).Execute
	/Users/sourishkrout/Projects/stateful/oss/runme/internal/runner/service.go:429
github.com/stateful/runme/internal/gen/proto/go/runme/runner/v1._RunnerService_Execute_Handler
	/Users/sourishkrout/Projects/stateful/oss/runme/internal/gen/proto/go/runme/runner/v1/runner_grpc.pb.go:246
google.golang.org/grpc.(*Server).processStreamingRPC
	/Users/sourishkrout/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:1668
google.golang.org/grpc.(*Server).handleStream
	/Users/sourishkrout/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:1755
google.golang.org/grpc.(*Server).serveStreams.func1.1
	/Users/sourishkrout/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:986
runtime.goexit
	/opt/homebrew/Cellar/go/1.21.3/libexec/src/runtime/asm_arm64.s:1197
```

**Comment by sourishkrout** [comment]
Perhaps you remember this @adambabik?

**Comment by adambabik** [comment]
I took a quick look:
- runner's code uses `exec.Cmd.Wait()` from stdlib which can return `exec.ExitError` but can also return a generic error.
- `exitCodeFromErr()` which translates the error to exit code only recognises `exec.ExitError`; otherwise it returns -1.
- Later, [the logic](https://github.com/stateful/rdme/blob/25f12ee8b5058483c43f57f05473ba04a6d810a7/internal/runner/service.go#L447) merely logs if the exit code is equal to -1 and does not handle it in any way.

We should omit `ExitCode` from the `ExecuteResponse` message when the exit code is -1 to indicate that the exit code is unknown. If the extension needs more information about internal errors (context cancelled, I/O error), we can introduce a new field.

In practice, exit codes range from 0 to 255, but there are [a lot of corner cases](https://unix.stackexchange.com/a/418802)... 
> Generally, you'd want to only use values 0 (generally meaning success) to 125 only, as many shells use values above 128 in their $? representation of the exit status to encode the signal number of a process being killed and 126 and 127 for special conditions.

**Comment by sourishkrout** [comment]
> We should omit `ExitCode` from the `ExecuteResponse` message when the exit code is -1 to indicate that the exit code is unknown. If the extension needs more information about internal errors (context cancelled, I/O error), we can introduce a new field.

I agree, that was my first thought, too. I'll take a stab at it once I'm done with my current task. It looks like this problem is currently not all too frequent, thankfully.

**Comment by sourishkrout** [comment]
Fixed as per https://github.com/stateful/runme/pull/445.
