### ISSUE TITLE
Port code block functions from the VS Code codebase

### ISSUE THREAD

**Issue by adambabik** [stateful/runme#72]
- Metadata (`cells = toCells()` and `serializeCells(cells)` should retain them). Add also `name` which will be consistent with the CLI.
- Language detection.
- Language names normalization (TBD cc @sebastian).

**Comment by adambabik** [comment]
Language detection is tracked in https://github.com/stateful/runme/issues/77.

**Comment by adambabik** [comment]
@sourishkrout what do you want to do in `Language names normalization (TBD cc @sebastian).`?

**Comment by sourishkrout** [comment]
Do you mean where `bash` becomes `sh` but also `bat` becomes `sh`? Trying to figure out what `language names normalization` is?

**Comment by adambabik** [comment]
@sourishkrout that was it. Thanks!

**Comment by sourishkrout** [comment]
The existing implementation is very Unix/Linux/macOS centric where it just assumes shell is inevitable which is why `bat` will be turned into `sh`. I think we want to account for a future where we want to support e.g. PowerShell on Windows. However, the `guesslang` model is basically platform agnostic so the best we can do is look at the execution context (platform identifier passed down) to make assumptions.

Making sure it's possible to pass down the execution context's platform (`darwin`, `win`, `linux`, etc) but only handle non-Win is probably all we need for now.
